### PR TITLE
Switch to `url.URL`, updates and audit

### LINKED ISSUE #72: "'url.parse' was deprecated since v11.0.0. Use 'url.URL' constructor instead"
Note: currently being used without base URL/host a lot, so the implementation needs to be changed a bit.

Also, the warning is slightly wrong in that you can just use the vanilla (WHATWG) `URL` constructor instead of having to import `url` at all anymore.

### PR DESCRIPTION
**Pull request by silverbucket**
* Update node versions: `18`, `20`, `21`
* Run linting before tests
* Update `mocha` due to security vulnerability
* Run `npm audit fix`
* Remove `eslint-plugin-standard`
* Set `eslint` to fail on linting warnings
* Fix linting warnings
* Make use of `url.URL` which securely handles path traversals and means we no longer need to protect against it.

Resolves #72 and for context #31

### CODE REVIEW

File: lib/armadietto.js [hunk 1]
```diff
@@ -139,63 +139,55 @@ class Armadietto {
 
   async dispatch (req, res) {
     const method = req.method.toUpperCase();
-    const uri = url.parse(req.url, true);
+    let pathname = new url.URL(req.url, `http://${this._options.http.host}${req.url}`).pathname;
```
Comment (DougReeder) [inline lib/armadietto.js:142]: This is fine. 

As [the docs](https://nodejs.org/docs/latest/api/url.html#new-urlinput-base) note "URL class is also available on the global object". So, when we do future work, we can use `new URL(...`

**Review by DougReeder — APPROVED** [review]
LGTM - it will be nice to not see the warnings about urls anymore!

File: lib/armadietto.js (hunk 1 above)
Comment (silverbucket) [reply lib/armadietto.js]: Ah yes, not sure why I didn't think of that. I've gone ahead and switched it per your comment, as it also means we don't have to `require("url")`
